version: '3.4'

services:
  redis:
    container_name: daprdemo-redis
    image: "redis"
    command: [
      "redis-server"
    ]
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: daprdemo-rabbitmq
    image: rabbitmq:3-management
    hostname: my-rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
  
  smtp:
    container_name: daprdemo-smtp4dev
    image: rnwood/smtp4dev
    ports:
      - "3000:80"
      - "2525:25"

  zipkin:
    container_name: daprdemo-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  
  memcached:
    container_name: daprdemo-memcached
    image: memcached
    ports:
      - "11211:11211"