apiVersion: apps/v1
kind: Deployment
metadata:
  name: daprdemoweb
  namespace: daprdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daprdemoweb
  template:
    metadata:
      labels:
        app: daprdemoweb
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprdemoweb"
        dapr.io/app-port: "80"
        dapr.io/config: "daprconfig"
    spec:
      containers:
      - name: daprdemoweb
        image: rgvna258/daprdemoweb:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: daprdemoweb
  namespace: daprdemo
spec:
  selector:
    app: daprdemoweb
  ports:
  - port: 5002
    targetPort: 80
  type: LoadBalancer