apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: daprdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: daprdemo
spec:
  selector:
    app: rabbitmq
  ports:
  - name: tcp
    port: 5672
    targetPort: 5672
  - name: tcp-management
    port: 15673
    targetPort: 15672
  type: LoadBalancer