apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: daprdemo
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6381
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
scopes:
  - daprdemoweb