apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: E:\Technologies\dapr\Repositories\DaprDemoApp\files\secrets.json
  - name: nestedSeparator
    value: ":"