apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: notification
spec:
  type: bindings.smtp
  version: v1
  metadata:
  - name: host
    value: "localhost"
  - name: "port"
    value: 2525
  - name: "user"
    value: ""
  - name: "password"
    value: ""
  - name: emailFrom
    value: "sender@example.com"
  - name: emailTo
    value: "receiver@example.com"
  - name: subject
    value: "DaprDemoApp Published Message"
scopes:
  - daprdemosubscriber